### ISSUE TITLE
Node16 leaks [GeoTools] [BreakdownTrees]

### ISSUE THREAD

**Issue by aruniverse** [iTwin/viewer-components-react#395]
After upgrading to node 16, there were some leaks in test code for the following 2 pkgs
Cover scripts were updated to skip these tests for the time being.

==[ FAILURE: 2 operations ]====================================================

--[ FAILURE: @itwin/breakdown-trees-react ]-----------------[ 11.02 seconds ]--

This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    at div
    at div
    at div
    at TreeNode (/home/vsts/work/1/s/common/temp/node_modules/.pnpm/@itwin+core-react@3.1.2_192e986a3ccac8c463840e3cecabb201/node_modules/@itwin/core-react/lib/cjs/core-react/tree/Node.js:27:9)
    at div
    at div
    at TreeNodeWrapper (/home/vsts/work/1/s/packages/itwin/breakdown-trees/lib/cjs/Views/NodeRenderers/FunctionalTreeNodeRenderer.js:61:9)
  ...2 lines omitted...
    at div
    at div
    at TreeNode (/home/vsts/work/1/s/common/temp/node_modules/.pnpm/@itwin+core-react@3.1.2_192e986a3ccac8c463840e3cecabb201/node_modules/@itwin/core-react/lib/cjs/core-react/tree/Node.js:27:9)
    at div
    at div
    at TreeNodeWrapper (/home/vsts/work/1/s/packages/itwin/breakdown-trees/lib/cjs/Views/NodeRenderers/FunctionalTreeNodeRenderer.js:61:9)
    at WrapperComponent (/home/vsts/work/1/s/common/temp/node_modules/.pnpm/@wojtekmaj+enzyme-adapter-utils@0.1.4_react@17.0.2/node_modules/@wojtekmaj/enzyme-adapter-utils/build/createMountWrapper.js:111:7)
##[error]Handle leak detected. Node was still running 5 seconds after tests completed.
Try running with the DEBUG_LEAKS env var set to see open handles.
Terminated

--[ FAILURE: @itwin/geo-tools-react ]-----------------------[ 14.01 seconds ]--

This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
This browser doesn't support cancelAnimationFrame. Make sure that you load a polyfill in older browsers. https://reactjs.org/link/react-polyfills
##[error]Handle leak detected. Node was still running 5 seconds after tests completed.
Try running with the DEBUG_LEAKS env var set to see open handles.
Terminated

Operations failed.

rush cover (1 minute 49.7 seconds)
##[error]Bash exited with code '1'.

**Comment by aruniverse** [comment]
Also, reports-config, [see](https://dev.azure.com/imodeljs/imodeljs/_build/results?buildId=6118&view=logs&j=ba8d0277-fee8-5755-bfec-5dace8f288bf&t=2c508f0f-406f-5aee-923e-1cfefd84d763&l=662)

==[ FAILURE: 1 operation ]=====================================================

--[ FAILURE: @itwin/reports-config-widget-react ]---[ 1 minute 52.7 seconds ]--

PASS src/test/ReportMappingHorizontalTile.test.tsx (58.072 s)
FAIL src/test/ReportMappings.test.tsx (65.933 s)
  ● Console

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one.

      at printWarning (../../../common/temp/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-test-utils.development.js:67:30)
      at error (../../../common/temp/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-test-utils.development.js:43:5)
      at onDone (../../../common/temp/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-test-utils.development.js:1034:9)
  ...20 lines omitted...
PASS src/test/AddMappingModal.test.tsx (23.223 s)
PASS src/test/DeleteModal.test.tsx (13.853 s)
PASS src/test/ReportAction.test.tsx (34.155 s)
PASS src/test/WidgetHeader.test.tsx (11.103 s)

Test Suites: 1 failed, 7 passed, 8 total
Tests:       1 failed, 40 passed, 41 total
Snapshots:   0 total
Time:        107.057 s
Ran all test suites.


rush cover (3 minutes 31.0 seconds)
Operations failed.
